-- MySQL Script generated by MySQL Workbench
-- Sun May  2 14:28:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Reward_Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reward_Profile` (
  `reward_id` VARCHAR(36) NOT NULL,
  `points` INT NULL DEFAULT 0,
  PRIMARY KEY (`reward_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `username` VARCHAR(36) NOT NULL,
  `birth_date` DATE NOT NULL,
  `user_tags` VARCHAR(100) NULL,
  `password` VARCHAR(45) NOT NULL,
  `reward_profile_id` VARCHAR(36) NOT NULL,
  `avatar_path` VARCHAR(260) NULL,
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_User_Reward_Profile1_idx` (`reward_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_Reward_Profile`
    FOREIGN KEY (`reward_profile_id`)
    REFERENCES `mydb`.`Reward_Profile` (`reward_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Advert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Advert` (
  `advert_id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `message` VARCHAR(100) NOT NULL,
  `photo_path` VARCHAR(260) NULL,
  `link` VARCHAR(50) NOT NULL,
  `frequency` FLOAT NULL,
  `video_path` VARCHAR(260) NULL,
  PRIMARY KEY (`advert_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Post` (
  `post_id` VARCHAR(36) NOT NULL,
  `message` VARCHAR(200) NULL,
  `post_tags` VARCHAR(100) NULL,
  `likes` INT NOT NULL DEFAULT 0,
  `username_id` VARCHAR(36) NOT NULL,
  `photo_path` VARCHAR(260) NULL,
  `video_path` VARCHAR(260) NULL,
  `post_date` DATE NULL,
  PRIMARY KEY (`post_id`),
  INDEX `fk_Post_User1_idx` (`username_id` ASC) VISIBLE,
  CONSTRAINT `fk_Username_Post`
    FOREIGN KEY (`username_id`)
    REFERENCES `mydb`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comment` (
  `comment_id` VARCHAR(36) NOT NULL,
  `message` VARCHAR(100) NOT NULL,
  `post_id` VARCHAR(36) NOT NULL,
  `username` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `fk_Comment_Post1_idx` (`post_id` ASC) VISIBLE,
  INDEX `fk_Comment_User1_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_Post_ID`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`Post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Username_Comment`
    FOREIGN KEY (`username`)
    REFERENCES `mydb`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
